### ISSUE TITLE
Update to 1.20.6 Please

### ISSUE THREAD

**Issue by sternschnaube** [adibarra/enchant-tweaker#36]
### What happened?

<details>
<summary> View Log </summary>
[EnchantTweaker] Mod enabled! Enabling mixins...
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1884 (java.lang.ClassNotFoundException: net/minecraft/class_1884)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1884 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1892 (java.lang.ClassNotFoundException: net/minecraft/class_1892)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1892 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1908 (java.lang.ClassNotFoundException: net/minecraft/class_1908)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1908 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1897 (java.lang.ClassNotFoundException: net/minecraft/class_1897)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1897 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1907 (java.lang.ClassNotFoundException: net/minecraft/class_1907)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1907 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1895 (java.lang.ClassNotFoundException: net/minecraft/class_1895)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1895 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1878 (java.lang.ClassNotFoundException: net/minecraft/class_1878)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1878 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1879 (java.lang.ClassNotFoundException: net/minecraft/class_1879)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1879 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1904 (java.lang.ClassNotFoundException: net/minecraft/class_1904)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1904 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1902 (java.lang.ClassNotFoundException: net/minecraft/class_1902)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1902 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1903 (java.lang.ClassNotFoundException: net/minecraft/class_1903)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1903 was not found enchanttweaker.mixins.json:server.capmod.GenericEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1912 (java.lang.ClassNotFoundException: net/minecraft/class_1912)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1912 was not found enchanttweaker.mixins.json:server.capmod.SpecialEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1905 (java.lang.ClassNotFoundException: net/minecraft/class_1905)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1905 was not found enchanttweaker.mixins.json:server.capmod.SpecialEnchantMixin from mod enchanttweaker
[20:08:55] [main/WARN]: Error loading class: net/minecraft/class_1877 (java.lang.ClassNotFoundException: net/minecraft/class_1877)
[20:08:55] [main/WARN]: @Mixin target net.minecraft.class_1877 was not found enchanttweaker.mixins.json:server.capmod.SpecialEnchantMixin from mod enchanttweaker
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1884 (java.lang.ClassNotFoundException: net/minecraft/class_1884)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1892 (java.lang.ClassNotFoundException: net/minecraft/class_1892)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1908 (java.lang.ClassNotFoundException: net/minecraft/class_1908)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1897 (java.lang.ClassNotFoundException: net/minecraft/class_1897)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1907 (java.lang.ClassNotFoundException: net/minecraft/class_1907)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1895 (java.lang.ClassNotFoundException: net/minecraft/class_1895)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1878 (java.lang.ClassNotFoundException: net/minecraft/class_1878)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1879 (java.lang.ClassNotFoundException: net/minecraft/class_1879)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1904 (java.lang.ClassNotFoundException: net/minecraft/class_1904)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1902 (java.lang.ClassNotFoundException: net/minecraft/class_1902)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1903 (java.lang.ClassNotFoundException: net/minecraft/class_1903)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1884 (java.lang.ClassNotFoundException: net/minecraft/class_1884)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1892 (java.lang.ClassNotFoundException: net/minecraft/class_1892)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1908 (java.lang.ClassNotFoundException: net/minecraft/class_1908)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1897 (java.lang.ClassNotFoundException: net/minecraft/class_1897)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1907 (java.lang.ClassNotFoundException: net/minecraft/class_1907)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1895 (java.lang.ClassNotFoundException: net/minecraft/class_1895)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1878 (java.lang.ClassNotFoundException: net/minecraft/class_1878)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1879 (java.lang.ClassNotFoundException: net/minecraft/class_1879)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1904 (java.lang.ClassNotFoundException: net/minecraft/class_1904)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1902 (java.lang.ClassNotFoundException: net/minecraft/class_1902)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1903 (java.lang.ClassNotFoundException: net/minecraft/class_1903)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1887$class_1888 (java.lang.ClassNotFoundException: net/minecraft/class_1887$class_1888)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1912 (java.lang.ClassNotFoundException: net/minecraft/class_1912)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1905 (java.lang.ClassNotFoundException: net/minecraft/class_1905)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1877 (java.lang.ClassNotFoundException: net/minecraft/class_1877)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1887$class_1888 (java.lang.ClassNotFoundException: net/minecraft/class_1887$class_1888)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1912 (java.lang.ClassNotFoundException: net/minecraft/class_1912)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1905 (java.lang.ClassNotFoundException: net/minecraft/class_1905)
[20:08:56] [main/WARN]: Error loading class: net/minecraft/class_1877 (java.lang.ClassNotFoundException: net/minecraft/class_1877)
[20:08:56] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[20:09:03] [main/WARN]: @Redirect conflict. Skipping companion.mixins.json:PlayerMixinFailsafe from mod companion->@Redirect::nullifyDefaultRemoveEntitiesOnShoulder(Lnet/minecraft/class_1657;)V with priority 950, already redirected by carpet.mixins.json:Player_parrotMixin from mod carpet->@Redirect::cancelDropShoulderEntities1(Lnet/minecraft/class_1657;)V with priority 1000
[20:09:03] [main/WARN]: @Redirect conflict. Skipping companion.mixins.json:PlayerMixinFailsafe from mod companion->@Redirect::nullifyDefaultRemoveEntitiesOnShoulder(Lnet/minecraft/class_1657;)V with priority 950, already redirected by carpet.mixins.json:Player_parrotMixin from mod carpet->@Redirect::cancelDropShoulderEntities2(Lnet/minecraft/class_1657;)V with priority 1000
[20:09:26] [main/ERROR]: Mixin apply for mod enchanttweaker failed enchanttweaker.mixins.json:server.capmod.ProtectionEnchantMixin from mod enchanttweaker -> net.minecraft.class_1900: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyReturnValue annotation on enchanttweaker$protectionEnchant$modifyMaxLevel could not find any targets matching 'Lnet/minecraft/class_1900;method_8183()I' in net.minecraft.class_1900. Using refmap enchanttweaker-refmap.json [PREINJECT Applicator Phase -> enchanttweaker.mixins.json:server.capmod.ProtectionEnchantMixin from mod enchanttweaker -> Prepare Injections ->  -> modifyReturnValue$zio000$enchanttweaker$protectionEnchant$modifyMaxLevel(I)I -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyReturnValue annotation on enchanttweaker$protectionEnchant$modifyMaxLevel could not find any targets matching 'Lnet/minecraft/class_1900;method_8183()I' in net.minecraft.class_1900. Using refmap enchanttweaker-refmap.json [PREINJECT Applicator Phase -> enchanttweaker.mixins.json:server.capmod.ProtectionEnchantMixin from mod enchanttweaker -> Prepare Injections ->  -> modifyReturnValue$zio000$enchanttweaker$protectionEnchant$modifyMaxLevel(I)I -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at com.llamalad7.mixinextras.injector.MixinExtrasInjectionInfo.<init>(MixinExtrasInjectionInfo.java:10) ~[mixinextras-0.3.5-63e25e1b0e82f847.jar:?]
	at com.llamalad7.mixinextras.injector.ModifyReturnValueInjectionInfo.<init>(ModifyReturnValueInjectionInfo.java:14) ~[mixinextras-0.3.5-63e25e1b0e82f847.jar:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_7923.method_47471(class_7923.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47485(class_7923.java:232) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47482(class_7923.java:247) ~[server-intermediary.jar:?]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986) [?:?]
	at net.minecraft.class_7923.method_47487(class_7923.java:245) [server-intermediary.jar:?]
	at net.minecraft.class_2966.redirect$zpa000$fabric-registry-sync-v0$initialize(class_2966.java:565) [server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:66) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server.jar:1.0.1]
[20:09:27] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1900 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_7923.method_47471(class_7923.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47485(class_7923.java:232) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47482(class_7923.java:247) ~[server-intermediary.jar:?]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986) ~[?:?]
	at net.minecraft.class_7923.method_47487(class_7923.java:245) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.redirect$zpa000$fabric-registry-sync-v0$initialize(class_2966.java:565) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server.jar:1.0.1]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	... 17 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [enchanttweaker.mixins.json:server.capmod.ProtectionEnchantMixin from mod enchanttweaker] from phase [DEFAULT] in config [enchanttweaker.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyReturnValue annotation on enchanttweaker$protectionEnchant$modifyMaxLevel could not find any targets matching 'Lnet/minecraft/class_1900;method_8183()I' in net.minecraft.class_1900. Using refmap enchanttweaker-refmap.json [PREINJECT Applicator Phase -> enchanttweaker.mixins.json:server.capmod.ProtectionEnchantMixin from mod enchanttweaker -> Prepare Injections ->  -> modifyReturnValue$zio000$enchanttweaker$protectionEnchant$modifyMaxLevel(I)I -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at com.llamalad7.mixinextras.injector.MixinExtrasInjectionInfo.<init>(MixinExtrasInjectionInfo.java:10) ~[mixinextras-0.3.5-63e25e1b0e82f847.jar:?]
	at com.llamalad7.mixinextras.injector.ModifyReturnValueInjectionInfo.<init>(ModifyReturnValueInjectionInfo.java:14) ~[mixinextras-0.3.5-63e25e1b0e82f847.jar:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	... 17 more
</details>

### What should have happened?

/

### How to reproduce?

Enabled the rule "capmod_enabled". 

### What is the jar file name?

enchanttweaker-1.4.9+mc1.20.3-1.20.4

### What Minecraft version?

Fabric 1.20.6

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Hello, MC 1.20.6 came with significant changes to Minecraft's internal code, which would require substantial changes to this mod's code. As of right now, I don't have the time to dedicate to it and refactor everything. So, unfortunately, I will no longer be updating the mod for new versions of MC.

However, if anyone is interested in continuing to update the mod by opening Pull Requests (or forking), feel free to do so, and I'll look at it as soon as possible.

**Comment by venaminecraft** [comment]
Thanks for making this clear!

**Comment by IVIPOWER** [comment]
oh, i see now, thx, idc when it comes out, if it does come out, id love to have it on 1.21, but i dont want to pressure the creator and this seems fair reason to leave it
